import React, { useState, useCallback, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Share,
  Animated,
  Dimensions,
} from 'react-native';
import { Stack, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { categories } from '../src/data/excuses';

const { width } = Dimensions.get('window');

export default function ExcuseScreen() {
  const { categoryId } = useLocalSearchParams<{ categoryId: string }>();
  const category = categories.find((c) => c.id === categoryId) ?? categories[0];

  const [usedIndices, setUsedIndices] = useState<number[]>([]);
  const [currentExcuse, setCurrentExcuse] = useState(() => {
    const idx = Math.floor(Math.random() * category.excuses.length);
    return { text: category.excuses[idx], index: idx };
  });

  const fadeAnim = useRef(new Animated.Value(1)).current;
  const scaleAnim = useRef(new Animated.Value(1)).current;

  const getNextExcuse = useCallback(() => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);

    // Animate out
    Animated.parallel([
      Animated.timing(fadeAnim, {
        toValue: 0,
        duration: 150,
        useNativeDriver: true,
      }),
      Animated.timing(scaleAnim, {
        toValue: 0.9,
        duration: 150,
        useNativeDriver: true,
      }),
    ]).start(() => {
      // Pick a new random excuse (avoid repeats until all used)
      let available = category.excuses
        .map((_, i) => i)
        .filter((i) => !usedIndices.includes(i) && i !== currentExcuse.index);

      if (available.length === 0) {
        setUsedIndices([]);
        available = category.excuses
          .map((_, i) => i)
          .filter((i) => i !== currentExcuse.index);
      }

      const nextIdx = available[Math.floor(Math.random() * available.length)];
      setUsedIndices((prev) => [...prev, currentExcuse.index]);
      setCurrentExcuse({ text: category.excuses[nextIdx], index: nextIdx });

      // Animate in
      fadeAnim.setValue(0);
      scaleAnim.setValue(1.05);
      Animated.parallel([
        Animated.timing(fadeAnim, {
          toValue: 1,
          duration: 250,
          useNativeDriver: true,
        }),
        Animated.spring(scaleAnim, {
          toValue: 1,
          useNativeDriver: true,
          friction: 8,
        }),
      ]).start();
    });
  }, [category, currentExcuse, usedIndices, fadeAnim, scaleAnim]);

  const handleShare = async () => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    try {
      await Share.share({
        message: `${category.emoji} ${category.name}\n\n"${currentExcuse.text}"\n\n— Generated by Excuse Me! app`,
      });
    } catch {}
  };

  const handleCopy = () => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    // React Native doesn't have clipboard by default, so we'll share instead
    handleShare();
  };

  return (
    <View style={styles.container}>
      <Stack.Screen
        options={{
          title: category.name,
          headerStyle: { backgroundColor: '#0f0f1a' },
        }}
      />

      {/* Category badge */}
      <View style={[styles.badge, { backgroundColor: category.color + '20' }]}>
        <Text style={styles.badgeEmoji}>{category.emoji}</Text>
        <Text style={[styles.badgeText, { color: category.color }]}>
          {category.name}
        </Text>
      </View>

      {/* Excuse Card */}
      <Animated.View
        style={[
          styles.excuseCard,
          {
            borderColor: category.color + '30',
            opacity: fadeAnim,
            transform: [{ scale: scaleAnim }],
          },
        ]}
      >
        <Text style={styles.quoteOpen}>"</Text>
        <Text style={styles.excuseText}>{currentExcuse.text}</Text>
        <Text style={styles.quoteClose}>"</Text>
      </Animated.View>

      {/* Action buttons */}
      <View style={styles.actions}>
        <TouchableOpacity
          style={[styles.actionBtn, styles.shareBtn]}
          onPress={handleShare}
        >
          <Ionicons name="share-outline" size={20} color="#fff" />
          <Text style={styles.actionBtnText}>Share</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.actionBtn, styles.copyBtn]}
          onPress={handleCopy}
        >
          <Ionicons name="copy-outline" size={20} color="#fff" />
          <Text style={styles.actionBtnText}>Copy</Text>
        </TouchableOpacity>
      </View>

      {/* Next button */}
      <TouchableOpacity
        style={[styles.nextBtn, { backgroundColor: category.color }]}
        onPress={getNextExcuse}
        activeOpacity={0.8}
      >
        <Text style={styles.nextBtnText}>Next Excuse</Text>
        <Ionicons name="shuffle" size={22} color="#fff" />
      </TouchableOpacity>

      {/* Counter */}
      <Text style={styles.counter}>
        {usedIndices.length + 1} of {category.excuses.length} excuses seen
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f0f1a',
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
    marginBottom: 24,
  },
  badgeEmoji: { fontSize: 18 },
  badgeText: { fontSize: 14, fontWeight: '700' },
  excuseCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: 24,
    padding: 32,
    width: width - 40,
    minHeight: 200,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  quoteOpen: {
    position: 'absolute',
    top: 16,
    left: 20,
    fontSize: 48,
    color: '#333',
    fontFamily: 'Georgia',
  },
  quoteClose: {
    position: 'absolute',
    bottom: 8,
    right: 20,
    fontSize: 48,
    color: '#333',
    fontFamily: 'Georgia',
  },
  excuseText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#eee',
    textAlign: 'center',
    lineHeight: 30,
    paddingHorizontal: 10,
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
  },
  shareBtn: { backgroundColor: '#2a2a3e' },
  copyBtn: { backgroundColor: '#2a2a3e' },
  actionBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  nextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: width - 40,
    paddingVertical: 18,
    borderRadius: 18,
    marginTop: 24,
  },
  nextBtnText: { color: '#fff', fontSize: 18, fontWeight: '800' },
  counter: {
    color: '#444',
    fontSize: 12,
    marginTop: 16,
  },
});
